// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXczNAAAA4wHjaeLsTHRicm0Mgqurstak',
    appId: '1:79484622548:web:e985f83c9820b3b8d70d41',
    messagingSenderId: '79484622548',
    projectId: 'bears-kitchen-5f546',
    authDomain: 'bears-kitchen-5f546.firebaseapp.com',
    storageBucket: 'bears-kitchen-5f546.firebasestorage.app',
    measurementId: 'G-4F2M6CDNPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdNG1nNspbdY1sTuiKlNmDKsv-mqJ6q8',
    appId: '1:79484622548:android:50da4e643f03e2c2d70d41',
    messagingSenderId: '79484622548',
    projectId: 'bears-kitchen-5f546',
    storageBucket: 'bears-kitchen-5f546.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgn8S8gOlCIQZYuXLM44xPcd1FD8FXVFk',
    appId: '1:79484622548:ios:2e3450491891bd79d70d41',
    messagingSenderId: '79484622548',
    projectId: 'bears-kitchen-5f546',
    storageBucket: 'bears-kitchen-5f546.firebasestorage.app',
    iosBundleId: 'com.example.dkuBearsKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgn8S8gOlCIQZYuXLM44xPcd1FD8FXVFk',
    appId: '1:79484622548:ios:2e3450491891bd79d70d41',
    messagingSenderId: '79484622548',
    projectId: 'bears-kitchen-5f546',
    storageBucket: 'bears-kitchen-5f546.firebasestorage.app',
    iosBundleId: 'com.example.dkuBearsKitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXczNAAAA4wHjaeLsTHRicm0Mgqurstak',
    appId: '1:79484622548:web:f79dbf4c8b8aa7e1d70d41',
    messagingSenderId: '79484622548',
    projectId: 'bears-kitchen-5f546',
    authDomain: 'bears-kitchen-5f546.firebaseapp.com',
    storageBucket: 'bears-kitchen-5f546.firebasestorage.app',
    measurementId: 'G-5TG8MSYZ7K',
  );
}
